-- script to create a cities table

"CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;"
USE_DATABASE_SQL="USE $DATABASE_NAME;"
CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    state_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    UNIQUE(id),
    FOREIGN KEY (state_id) REFERENCES states(id)
);"
